---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

_Last updated: April 16, 2025 by Andrey Vega Alfaro_

# geneticMapRFiles

This repository stores data files used alongside the `geneticMapR` R package.

## Repository Purpose

This data-only repository hosts example and large-scale datasets used for development, testing, and demonstration of the `geneticMapR` package. These datasets are not included in the main CRAN package due to size limitations.

## Folder Structure

- `IDs`: Sample names and pedigree
- `phenotype`: phenotypic data 
- `vcf`: genotypic data, usually in vcf format.
- `R_data`: RDAs and other R objects and datasets.

## Usage

These files can be accessed in your R workflows by downloading them directly or by linking this GitHub repo in your pipeline.

## Related Package

See the main package: [`geneticMapR`](https://github.com/vegaalfaro/geneticMapR)

## License

MIT

## Files Description

### IDs
- `ID-Pedigrees-Biparentals-2025-01-22.xlsx`: This table contains sample-level metadata for individuals in a genetic study which corresponds to samples in a VCF file and downstream analysis.


### phenotype

### R_data

### vcf



